matrix:
  include:
    - scala: 2.10.6
      jdk: oraclejdk8
      env: PLATFORM="jvm"
      script: sbt coreJVM/test catsJVM/test

    - scala: 2.10.6
      jdk: oraclejdk8
      env: PLATFORM="js"
      script: sbt coreJS/test catsJS/test

    - scala: 2.11.8
      jdk: oraclejdk8
      env: PLATFORM="jvm"
      script: sbt coreJVM/test catsJVM/test

    - scala: 2.11.8
      jdk: oraclejdk8
      env: PLATFORM="js"
      script: sbt coreJS/test catsJS/test

    - scala: 2.12.1
      jdk: oraclejdk8
      env: PLATFORM="jvm"
      script: sbt coreJVM/test catsJVM/test

    - scala: 2.12.1
      jdk: oraclejdk8
      env: PLATFORM="js"
      script: sbt coreJS/test catsJS/test

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
